next try

diff --git a/.github/workflows/unittest.yml b/.github/workflows/unittest.yml
--- a/.github/workflows/unittest.yml
+++ b/.github/workflows/unittest.yml
@@ -39,6 +39,4 @@ jobs:
         run: |
           ghdl -a --std=93c --workdir=./sim/work ./bfm/eSpiStaticSlave.vhd
           ghdl -a --std=93c --workdir=./sim/work ./tb/eSpiStaticSlave_tb.vhd
-          ghdl -r --std=93c --workdir=./sim/work eSpiStaticSlave
-          ghdl -r --std=93c --workdir=./sim/work eSpiStaticSlave_tb
-          [[ -z $($(ghdl -e --workdir=./sim/work eSpiStaticSlave_tb) | grep "Test SUCCESSFUL") ]] && echo "FAIL" && exit 1
+          if [[ -z $(ghdl -r --workdir=./sim/work eSpiStaticSlave_tb | grep "Test SUCCESSFUL") ]]; then echo "FAIL"; exit 1; fi;
