eval tb "Test SUCCESSFUL" output to check if TB reached end

diff --git a/.github/workflows/unittest.yml b/.github/workflows/unittest.yml
--- a/.github/workflows/unittest.yml
+++ b/.github/workflows/unittest.yml
@@ -41,10 +41,10 @@ jobs:
         run: |
           ghdl -a ${GHDL_OPTS} ./bfm/eSpiStaticSlave.vhd
           ghdl -a ${GHDL_OPTS} ./tb/eSpiStaticSlave_tb.vhd
-          ((ghdl -r ${GHDL_OPTS} eSpiStaticSlave_tb -gDO_ALL_TEST=True) || if [ $? -ne 0 ]; then echo "[ FAIL ]   eSpiStaticSlave"; exit 1; fi)
+          if [[ -z $(ghdl -r ${GHDL_OPTS} eSpiStaticSlave_tb -gDO_ALL_TEST=True | grep "Test SUCCESSFUL") ]]; then echo "[ FAIL ]   eSpiStaticSlave"; exit 1; fi;
       - name: eSpiMasterBfm
         run: |
           ghdl -a ${GHDL_OPTS} ./bfm/eSpiStaticSlave.vhd
           ghdl -a ${GHDL_OPTS} ./bfm/eSpiMasterBfm.vhd
           ghdl -a ${GHDL_OPTS} ./tb/eSpiMasterBfm_tb.vhd
-          ((ghdl -r ${GHDL_OPTS} eSpiMasterBfm_tb -gDO_ALL_TEST=True) || if [ $? -ne 0 ]; then echo "[ FAIL ]   eSpiMasterBfm"; exit 1; fi)
+          if [[ -z $(ghdl -r ${GHDL_OPTS} eSpiMasterBfm_tb -gDO_ALL_TEST=True | grep "Test SUCCESSFUL") ]]; then echo "[ FAIL ]   eSpiMasterBfm"; exit 1; fi;
